### ISSUE TITLE
Speed display.

### ISSUE THREAD

**Issue by ghost** [Simoma/rena#15] opened 2017-07-06 13:34 UTC
Please calculate speed from position data. You coukd use a running average using the last six position measurements to get a speed readout which isnt to bouncy but still tells the rider not only distance but speed. This does not have to be saved in the GPX files, just a nice UI addition!

**Comment by Simoma** [comment] 2017-09-27 17:14
This appears to be a duplicate of #8 .

**Closed as completed by Simoma** 2017-09-27 17:14 UTC
Labels: duplicate
